const Images = {
  background1: require('../../assets/images/home-background-1.jpg'),
  background2: require('../../assets/images/home-background-2.jpg'),
  background3: require('../../assets/images/home-background-3.jpg'),
  background4: require('../../assets/images/home-background-4.jpg'),
  background5: require('../../assets/images/home-background-5.jpg'),
  background6: require('../../assets/images/home-background.jpg'),
  news1: require('../../assets/images/newArrival.jpg'),
  news2: require('../../assets/images/sale1.jpg'),
  news3: require('../../assets/images/sale2.jpg'),
  arrival1: require('../../assets/images/dress1.jpg'),
  arrival2: require('../../assets/images/top1.jpg'),
  arrival3: require('../../assets/images/bottom1.jpg'),
  arrival4: require('../../assets/images/dress2.jpg'),
  arrival5: require('../../assets/images/top2.jpg'),
  arrival6: require('../../assets/images/bottom2.jpg'),
  arrival7: require('../../assets/images/dress3.jpg'),
  arrival8: require('../../assets/images/dress4.jpg'),
  arrival9: require('../../assets/images/dress5.jpg'),
  arrival10: require('../../assets/images/dress6.jpg'),
  arrival11: require('../../assets/images/top3.jpg'),
  arrival12: require('../../assets/images/top4.jpg'),
  arrival13: require('../../assets/images/bottom3.jpg'),
  arrival14: require('../../assets/images/bottom4.jpg'),
  // arrival15: require('../../assets/images/bottom5.jpg'),
};
export default Images;
